on: push
name: Slack Notification Demo
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - uses: rtCamp/action-slack-notify@v2
        if: always()
        with:
          status: ${{ job.status }} # required
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }} # required

