   - name: Report Status
  if: always()
  uses: pratik/notify-slack-action@v1
  with:
    status: ${{ job.status }}
    notify_when: 'failure'
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
