on: push
#1234
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      if: success()
      uses: rtCamp/action-slack-notify@v2
 
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEB }}
        #SLACK_WEBHOOK: ${{ secrets.INCOMING_WEBHOOK }}
        #SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
