on: push
name: Slack Notification Demo
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@main
      - name: Slack Notification Demo
        uses: voxmedia/github-action-slack-notify-build@v1
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: 'Demo''ing the Slack Notification'
          SLACK_TITLE: 'Slack Notification Demo'
        with:
          channel: app-alerts
          status: STARTED
          color: good

          
          
          
          

          
