on: push
#1234
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Slack Notification34
      uses: rtCamp/action-slack-notify@v2
 
      env:
        #SLACK_WEBHOOK: ${{ secrets.INCOMING_WEBHOOK }}
        #SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_TITLE: Post Title
        #SLACK_WEBHOOK: ${{ secrets.SLACK_WEB }}
        SLACK_WEBHOOK: ${{ secrets.SUPPORT_WEBHOOK}}
