

 on: push
 name: Slack Notification Demo
 jobs:
   slackNotification:
     name: Slack Notification
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
    

     - name: Report Status
       if: always()
       uses: ravsamhq/notify-slack-action@v1
       with:
         status: ${{ job.status }}
         notify_when: 'failure'
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.INCOMING_WEBHOOK }}
         status: ${{ job.status }} # required
         notify_when: 'failure'
         notification_title: '{workflow} has {status_message}'
         message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
         footer: 'Linked to Repo <{repo_url}|{repo}>'
 
