name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print success
        run: echo "success"
      - name: Print failure
        run: echo "failure"
      - name: slack-notify
      - uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }} 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.INCOMING_WEBHOOK }}

