on: push
name: Slack Notification Demo123
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify slack success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      with:
        status: SUCCESS
        color: good
    - name: Notify slack fail
      if: failure()
      with:
        status: FAILED
        color: danger

      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_URL }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}











